env:
    browser: true
    es2021: true
extends:
    - 'eslint:recommended'
    - 'plugin:@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
    ecmaVersion: 12
    sourceType: module
plugins:
    - '@typescript-eslint'
rules:
    {
        '@typescript-eslint/no-var-requires': 0,
        '@typescript-eslint/no-unused-vars': ['warn', { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' }],
    }
