# The image is needed so that every Gitpod Workspace comes with gitpod/workspace-full-vnc whenever they start it.
image:
  file: .gitpod.Dockerfile

# Now, there are specific tasks for dependencies, servers, noVNC, ports and even pre-builds so that you start without delay.
tasks:
  - name: Yarn Server
    init: echo "Starting server"
    command: |
          sudo sh .gitpod/server.sh

vscode:
  extensions:
    - kimlimjustin.jsdoc-generator
    - esbenp.prettier-vscode
    - orta.vscode.jest

# GitHub Prebuilds
github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
# enable for all branches in this repo (defaults to false)
    branches: true
# enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
# enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
# add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
    addComment: true
# add a "Review in Gitpod" button to pull requests (defaults to false)
    addBadge: true
# add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: prebuilt-in-gitpod
